### ISSUE TITLE
Using matchhistogram for HDR->SDR conversion

### ISSUE THREAD

**Issue by kriNon** [dubhater/vapoursynth-matchhistogram#1]
Hey,
So I have both a hdr and sdr version of the same video. I have matched the frames of both in vapoursynth, however the colour is obviously quite different. The HDR is actually a manual conversion done in studio and is based off of the SDR clip.

I've tried using match-histogram to adjust the colours of the two, and while it does work surprisingly better than I expected, it is still quite a ways off. One thing I've noticed is that colours still won't match perfectly. I'm not sure if this is a limitation in how match-histogram works, but I suspect maybe it's to do with the curves calculated for the conversion not being high enough resolution?

Was wondering if you had any ideas for how I could tackle this problem?

**Comment by dubhater** [comment]
Sorry, I don't know.

**Comment by kriNon** [comment]
alright, thanks anyways :)
